# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: integrationtest.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='integrationtest.proto',
  package='main',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x15integrationtest.proto\x12\x04main\"\x1a\n\tInt32Test\x12\r\n\x05value\x18\x01 \x01(\x05\"\x1b\n\nStringTest\x12\r\n\x05value\x18\x01 \x01(\tb\x06proto3')
)




_INT32TEST = _descriptor.Descriptor(
  name='Int32Test',
  full_name='main.Int32Test',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='value', full_name='main.Int32Test.value', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=31,
  serialized_end=57,
)


_STRINGTEST = _descriptor.Descriptor(
  name='StringTest',
  full_name='main.StringTest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='value', full_name='main.StringTest.value', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=59,
  serialized_end=86,
)

DESCRIPTOR.message_types_by_name['Int32Test'] = _INT32TEST
DESCRIPTOR.message_types_by_name['StringTest'] = _STRINGTEST
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Int32Test = _reflection.GeneratedProtocolMessageType('Int32Test', (_message.Message,), dict(
  DESCRIPTOR = _INT32TEST,
  __module__ = 'integrationtest_pb2'
  # @@protoc_insertion_point(class_scope:main.Int32Test)
  ))
_sym_db.RegisterMessage(Int32Test)

StringTest = _reflection.GeneratedProtocolMessageType('StringTest', (_message.Message,), dict(
  DESCRIPTOR = _STRINGTEST,
  __module__ = 'integrationtest_pb2'
  # @@protoc_insertion_point(class_scope:main.StringTest)
  ))
_sym_db.RegisterMessage(StringTest)


# @@protoc_insertion_point(module_scope)
